# Generated by Django 2.1.4 on 2019-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.CharField(default='玄幻', max_length=150),
        ),
        migrations.AddField(
            model_name='novel',
            name='writer',
            field=models.CharField(default='佚名', max_length=150),
        ),
    ]
