# Generated by Django 2.1.4 on 2019-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20190324_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=models.SlugField(default='玄幻'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='img_url',
            field=models.CharField(default='test.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_id',
            field=models.CharField(default='1111_00', max_length=150),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(default='无名', max_length=150),
        ),
    ]
