# Generated by Django 2.1.4 on 2019-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20190326_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(blank=True, default='玄幻'),
        ),
    ]
