# Generated by Django 2.1.4 on 2019-03-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20190326_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={},
        ),
        migrations.RemoveField(
            model_name='novel',
            name='slug',
        ),
    ]
