# Generated by Django 2.1.4 on 2019-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='brief_content',
            field=models.CharField(default='不错不错', max_length=150),
        ),
    ]
