# Generated by Django 2.1.4 on 2019-04-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_novel_brief_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='brief_content',
            field=models.CharField(default='不错不错', max_length=400),
        ),
    ]
