# Generated by Django 2.1.4 on 2019-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20190411_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_id', models.CharField(default='1111_00', max_length=150)),
                ('user_name', models.CharField(max_length=150)),
            ],
        ),
    ]
